.nh
.TH "GH-AUTH-TOKEN" "1" "Mar 2023" "GitHub CLI 2.24.3" "GitHub CLI manual"

.SH NAME
.PP
gh-auth-token - Print the auth token gh is configured to use


.SH SYNOPSIS
.PP
\fB\fCgh auth token [flags]\fR


.SH OPTIONS
.TP
\fB\fC-h\fR, \fB\fC--hostname\fR \fB\fC<string>\fR
The hostname of the GitHub instance authenticated with

.TP
\fB\fC--secure-storage\fR
Search only secure credential store for authentication token


.SH SEE ALSO
.PP
\fB\fCgh-auth(1)\fR
