.nh
.TH "GH-CODESPACE-LOGS" "1" "Mar 2023" "GitHub CLI 2.24.3" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-logs - Access codespace logs


.SH SYNOPSIS
.PP
\fB\fCgh codespace logs [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace

.TP
\fB\fC-f\fR, \fB\fC--follow\fR
Tail and follow the logs

.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<string>\fR
Filter codespace selection by repository name (user/repo)


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
