.nh
.TH "GH-CODESPACE-STOP" "1" "Mar 2023" "GitHub CLI 2.24.3" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-stop - Stop a running codespace


.SH SYNOPSIS
.PP
\fB\fCgh codespace stop [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace

.TP
\fB\fC-o\fR, \fB\fC--org\fR \fB\fC<login>\fR
The login handle of the organization (admin-only)

.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<string>\fR
Filter codespace selection by repository name (user/repo)

.TP
\fB\fC-u\fR, \fB\fC--user\fR \fB\fC<username>\fR
The username to stop codespace for (used with --org)


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
