.nh
.TH "GH-EXTENSION-BROWSE" "1" "Mar 2023" "GitHub CLI 2.24.3" "GitHub CLI manual"

.SH NAME
.PP
gh-extension-browse - Enter a UI for browsing, adding, and removing extensions


.SH SYNOPSIS
.PP
\fB\fCgh extension browse [flags]\fR


.SH DESCRIPTION
.PP
This command will take over your terminal and run a fully interactive
interface for browsing, adding, and removing gh extensions. A terminal
width greater than 100 columns is recommended.

.PP
To learn how to control this interface, press ? after running to see
the help text.

.PP
Press q to quit.

.PP
Running this command with --single-column should make this command
more intelligible for users who rely on assistive technology like screen
readers or high zoom.

.PP
For a more traditional way to discover extensions, see:

.PP
.RS

.nf
gh ext search

.fi
.RE

.PP
along with gh ext install, gh ext remove, and gh repo view.


.SH OPTIONS
.TP
\fB\fC--debug\fR
log to /tmp/extBrowse-*

.TP
\fB\fC-s\fR, \fB\fC--single-column\fR
Render TUI with only one column of text


.SH SEE ALSO
.PP
\fB\fCgh-extension(1)\fR
