.nh
.TH "GH-GPG-KEY-DELETE" "1" "Mar 2023" "GitHub CLI 2.24.3" "GitHub CLI manual"

.SH NAME
.PP
gh-gpg-key-delete - Delete a GPG key from your GitHub account


.SH SYNOPSIS
.PP
\fB\fCgh gpg-key delete <key-id> [flags]\fR


.SH OPTIONS
.TP
\fB\fC-y\fR, \fB\fC--yes\fR
Skip the confirmation prompt


.SH SEE ALSO
.PP
\fB\fCgh-gpg-key(1)\fR
