.nh
.TH "GH-ISSUE-DEVELOP" "1" "Mar 2023" "GitHub CLI 2.24.3" "GitHub CLI manual"

.SH NAME
.PP
gh-issue-develop - Manage linked branches for an issue


.SH SYNOPSIS
.PP
\fB\fCgh issue develop [flags] {<number> | <url>}\fR


.SH OPTIONS
.TP
\fB\fC-b\fR, \fB\fC--base\fR \fB\fC<string>\fR
Name of the base branch you want to make your new branch from

.TP
\fB\fC-c\fR, \fB\fC--checkout\fR
Checkout the branch after creating it

.TP
\fB\fC-i\fR, \fB\fC--issue-repo\fR \fB\fC<string>\fR
Name or URL of the issue's repository

.TP
\fB\fC-l\fR, \fB\fC--list\fR
List linked branches for the issue

.TP
\fB\fC-n\fR, \fB\fC--name\fR \fB\fC<string>\fR
Name of the branch to create


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
$ gh issue develop --list 123 # list branches for issue 123
$ gh issue develop --list --issue-repo "github/cli" 123 # list branches for issue 123 in repo "github/cli"
$ gh issue develop --list https://github.com/github/cli/issues/123 # list branches for issue 123 in repo "github/cli"
$ gh issue develop 123 --name "my-branch" --base my-feature # create a branch for issue 123 based on the my-feature branch
$ gh issue develop 123 --checkout # fetch and checkout the branch for issue 123 after creating it


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-issue(1)\fR
