.nh
.TH "GH-SSH-KEY-DELETE" "1" "Mar 2023" "GitHub CLI 2.24.3" "GitHub CLI manual"

.SH NAME
.PP
gh-ssh-key-delete - Delete an SSH key from your GitHub account


.SH SYNOPSIS
.PP
\fB\fCgh ssh-key delete <id> [flags]\fR


.SH OPTIONS
.TP
\fB\fC-y\fR, \fB\fC--yes\fR
Skip the confirmation prompt


.SH SEE ALSO
.PP
\fB\fCgh-ssh-key(1)\fR
