# Generated by Django 4.1.7 on 2023-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('cate', models.CharField(choices=[('Books', 'Books'), ('electronics', 'Electronic Component')], default='Books', max_length=20)),
                ('des', models.CharField(max_length=100)),
                ('type1', models.CharField(choices=[('new', 'NEW'), ('second', 'SECOND_HAND')], default='new', max_length=20)),
                ('filename', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
