# Generated by Django 4.1.7 on 2023-03-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('electronics', 'Electronic Component')], default='Books', max_length=20)),
                ('cost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], max_length=10)),
                ('payment_mode', models.CharField(choices=[('credit card', 'Credit card'), ('debit card', 'Debit card'), ('cash', 'Cash'), ('upi', 'UPI')], max_length=20)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('category', models.EmailField(max_length=30)),
                ('cost', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('waiting', 'Waiting')], max_length=10)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=2)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.product')),
            ],
        ),
    ]
