# Generated by Django 4.1.7 on 2023-03-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_orderitem_shippingaddress_remove_order_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
