# Generated by Django 4.1.7 on 2023-03-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_alter_buyer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
    ]
