# Generated by Django 4.1.7 on 2023-03-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0011_alter_buyer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
