# Generated by Django 4.1.7 on 2023-03-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0012_rename_customer_id_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
    ]
