# Generated by Django 4.1.7 on 2023-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0014_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(max_length=10),
        ),
    ]
