# Generated by Django 4.1.7 on 2023-03-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0015_alter_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
